import {byId,rounds} from './data.js';
import {archetypes} from './drama-data.js';
import {films,coalitionChanges,votingPairs} from './relationships.js';
const $=s=>document.querySelector(s), reduced=matchMedia('(prefers-reduced-motion:reduce)');
let motionAllowed=!reduced.matches;try{motionAllowed ||= localStorage.getItem('unseen-motion')==='on';}catch{}
const host=document.createElement('section');host.id='living-game';host.className='living-game';host.setAttribute('aria-label','The living game: animated coalition stories');
host.innerHTML=`<div class="cinema-top"><span>CELEBRITY TRAITORS · UK 1</span><span>HOW THE VOTING GROUPS CHANGED</span><span>FULL SERIES SPOILERS</span></div><div class="film-menu" role="group" aria-label="Choose a relationship story">${films.map((f,i)=>`<button data-film="${i}" aria-pressed="${i===0}"><small>0${i+1}</small>${f.title}<span>↗</span></button>`).join('')}</div><div class="cinema-heading"><span id="film-round"></span><h1 id="film-title"></h1><p id="film-caption"></p><button id="film-enable">▶ Bring the cards to life</button></div><div class="living-stage"><div class="stage-halo"></div><svg id="living-links" viewBox="0 0 1000 520" preserveAspectRatio="none" aria-hidden="true"></svg><div id="living-cast"></div><div class="cinema-verdict" id="cinema-verdict"></div><div class="film-choices" hidden><span>COULD ONE ALLY SAVE JOE?</span><button data-rescue="1">Move Nick to Alan</button><button data-rescue="2">Move David too</button><button data-rescue="0">Actual vote ↺</button></div><div class="cinema-key"><span>━ Voted together</span><span>⇢ Voted against</span><span>╱ Connection breaks</span></div></div><div class="cinema-controls"><button id="film-play" aria-label="Pause story">Ⅱ Pause</button><div class="film-scrubber"><div id="film-beats"></div><input id="film-time" type="range" min="0" max="1000" value="0" aria-label="Scrub through the coalition story"></div><button id="film-restart" aria-label="Replay story">↺</button><button id="film-share">Share ↗</button></div><div class="cinema-bottom"><span id="film-change"></span><button id="film-evidence">Follow the ballots ↓</button></div>`;
$('#main').prepend(host);
// Keep the older instrument available as a secondary close-up, not a competing opening.
const old=$('#theatre'),details=document.createElement('details');details.className='old-theatre';details.innerHTML='<summary>Open the six individual voting scenes <span>＋</span></summary>';old.before(details);details.append(old);
$('nav a[href="#theatre"]').href='#living-game';
let rescue=0;
let film=0,beat=-1,elapsed=0,playing=motionAllowed,last=0,inView=true,lastPhase=-1,currentNodes=[],total=0;
const cast=$('#living-cast'),svg=$('#living-links'),slider=$('#film-time');
function duration(){return films[film].beats.reduce((s,b)=>s+b.duration,0)}
function locate(t){let start=0;for(let i=0;i<films[film].beats.length;i++){const b=films[film].beats[i];if(t<start+b.duration||i===films[film].beats.length-1)return{i,local:t-start};start+=b.duration;}}
function setPlaying(value){playing=value;if(value){motionAllowed=true;try{localStorage.setItem('unseen-motion','on');}catch{}}host.dataset.motion=motionAllowed?'on':'off';$('#film-play').textContent=value?'Ⅱ Pause':'▶ Play';$('#film-play').setAttribute('aria-label',value?'Pause story':'Play story');}
function loadFilm(i,auto=true){film=i;beat=-1;elapsed=0;rescue=0;total=duration();lastPhase=-1;cast.innerHTML=films[i].cast.map(id=>{const p=byId[id],a=archetypes.findIndex(a=>a.id===id);return `<button class="actor ${p.role==='T'?'actor-traitor':''} ${a<0?'actor-minor':''}" data-actor="${id}" aria-label="${p.name}: watch their connections" style="--art-x:${(a%3)*50}%;--art-y:${a<3?0:100}%"><span class="actor-image">${a<0?`<i>${p.name.split(' ').map(s=>s[0]).join('')}</i>`:''}</span><span class="actor-role">${p.role==='T'?'TRAITOR':'FAITHFUL'}</span><span class="actor-name">${p.short}</span><span class="actor-ballot"></span><span class="actor-exit">OUT</span></button>`}).join('');currentNodes=films[i].cast.map(id=>({id,x:50,y:115,tx:50,ty:115,el:cast.querySelector(`[data-actor="${id}"]`)}));$('#film-beats').innerHTML=films[i].beats.map((b,j)=>`<button data-beat="${j}" aria-label="Scene ${j+1}: ${b.title}" style="flex:${b.duration}"><span>${j+1}</span></button>`).join('');host.querySelectorAll('[data-film]').forEach((b,j)=>b.setAttribute('aria-pressed',i===j));setPlaying(auto&&motionAllowed);paint(0);}
function paint(t){const point=locate(t),b=films[film].beats[point.i],r=rescue?{...rounds[b.round],votes:{...rounds[b.round].votes,nick:"alan",...(rescue===2?{david:"alan"}:{})}}:rounds[b.round];if(beat!==point.i){beat=point.i;lastPhase=-1;$('#film-round').textContent=`${b.ending?'THE PATTERN':'ROUND '+r.label} · ${beat+1} / ${films[film].beats.length}`;$('#film-title').textContent=b.title;$('#film-caption').textContent=b.caption;$('#cinema-verdict').textContent=rescue===1?'2–2. One ally creates a tie.':rescue===2?'3–1 against Alan. It takes both allies.':b.out;$('.film-choices').hidden=!(film===0&&b.ending);if(rescue){$('#film-title').textContent=rescue===1?'One ally is not enough.':'Two allies change the verdict.';$('#film-caption').textContent='YOUR ALTERNATE BALLOTS · all other votes held fixed';}host.classList.remove('cut');void host.offsetWidth;host.classList.add('cut');host.querySelectorAll('[data-beat]').forEach((el,i)=>el.setAttribute('aria-current',i===beat?'step':'false'));
 const previous=films[film].beats[Math.max(0,beat-1)].round,changes=coalitionChanges(previous,b.round);
 $('#film-change').textContent=beat===0?'A gold line joins players who voted for the same person.':b.ending?'Watch who changes sides between votes.':`${changes.broken.length} co-voting connections break · ${changes.joined.length} form`;
 currentNodes.forEach(n=>{const pos=rescue&&['nick','david','joe','alan'].includes(n.id)?({joe:[20,28],nick:[40,28],david:rescue===2?[60,28]:[82,70],alan:[42,76]}[n.id]):b.positions[n.id]||[95,95];n.tx=pos[0];n.ty=pos[1];const alive=r.candidates.includes(n.id);n.el.classList.toggle('actor-gone',!alive);n.el.classList.toggle('actor-focus',b.focus.includes(n.id));n.el.classList.toggle('actor-target',r.eliminated===n.id);n.el.querySelector('.actor-ballot').textContent=alive&&r.votes[n.id]?'→ '+byId[r.votes[n.id]].short: n.id==='lucy'?'MURDERED':'OUT';n.el.tabIndex=alive?0:-1;n.el.setAttribute('aria-label',`${byId[n.id].name}${alive?': votes '+byId[r.votes[n.id]]?.name:': out of the game'}`);});
 }
 const phase=b.ending?2:point.local> b.duration*.7?2:point.local>1100?1:0;
 if(phase!==lastPhase){lastPhase=phase;host.dataset.phase=phase;currentNodes.forEach(n=>n.el.classList.toggle('actor-banished',phase===2&&!b.ending&&r.eliminated===n.id));}
 slider.value=Math.round(t/total*1000);return {b,r,point,phase};}
function lines(state,now){const {b,r,point,phase}=state,map=Object.fromEntries(currentNodes.map(n=>[n.id,n]));let content='<defs><marker id="vote-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><polygon points="0,0 10,5 0,10" fill="#ef826c"/></marker></defs>';
 const line=(a,z,cls,extra='')=>{if(!map[a]||!map[z])return;const A=map[a],B=map[z];let ex=B.x*10,ey=B.y*5.2;if(cls==='accusation'){const dx=(B.x-A.x)*10,dy=(B.y-A.y)*5.2,rect=B.el.getBoundingClientRect(),stage=$('.living-stage').getBoundingClientRect(),hw=rect.width/stage.width*500+7,hh=rect.height/stage.height*260+7,k=Math.min(hw/Math.max(Math.abs(dx),.01),hh/Math.max(Math.abs(dy),.01));ex-=dx*k;ey-=dy*k;}content+=`<path class="${cls}" d="M ${A.x*10} ${A.y*5.2} Q ${(A.x+B.x)*5} ${(A.y+B.y)*2.6-24} ${ex} ${ey}" ${extra}/>`;};
 const previous=films[film].beats[Math.max(beat-1,0)].round;
 if(beat>0&&point.local<2600)coalitionChanges(previous,b.round).broken.forEach(([a,z])=>line(a,z,'bond breaking',`style="opacity:${1-point.local/2600}"`));
 (rescue?Object.keys(r.votes).flatMap((a,i,all)=>all.slice(i+1).filter(z=>r.votes[a]===r.votes[z]).map(z=>[a,z])):votingPairs(b.round)).forEach(([a,z])=>line(a,z,'bond',`style="opacity:${Math.min(point.local/1200,1)*.65}"`));
 if(phase>0)Object.entries(r.votes).forEach(([a,z])=>{if(!b.focus.includes(a)&&!b.focus.includes(z))return;line(a,z,'accusation',`marker-end="url(#vote-arrow)" style="stroke-dashoffset:${-now/28}"`);});
 svg.innerHTML=content;
}
function frame(now){if(now-last<32){requestAnimationFrame(frame);return;}const dt=Math.min(now-last||16,50);last=now;if(inView&&!document.hidden){if(playing&&!$('#tarot-dialog').open&&!$('#share-dialog').open){elapsed=Math.min(elapsed+dt,total);if(elapsed>=total)setPlaying(false);}const s=paint(elapsed);currentNodes.forEach(n=>{const ease=!motionAllowed?1:1-Math.exp(-dt/430);n.x+=(n.tx-n.x)*ease;n.y+=(n.ty-n.y)*ease;n.el.style.left=n.x+'%';n.el.style.top=n.y+'%';});lines(s,now);}requestAnimationFrame(frame);}
function seekBeat(i){rescue=0;elapsed=films[film].beats.slice(0,i).reduce((s,b)=>s+b.duration,0)+1500;setPlaying(false);paint(elapsed);}
host.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.rescue!==undefined){rescue=+button.dataset.rescue;beat=-1;setPlaying(false);paint(elapsed);return;}if(button.dataset.film!==undefined)loadFilm(+button.dataset.film);if(button.dataset.beat!==undefined)seekBeat(+button.dataset.beat);if(button.dataset.actor){setPlaying(false);const id=button.dataset.actor;document.dispatchEvent(new CustomEvent('unseen:tarot',{detail:id}));}switch(button.id){case'film-enable':elapsed=0;beat=-1;setPlaying(true);break;case'film-play':if(elapsed>=total)elapsed=0;setPlaying(!playing);break;case'film-restart':rescue=0;elapsed=0;beat=-1;setPlaying(true);break;case'film-share':setPlaying(false);document.dispatchEvent(new CustomEvent('unseen:share',{detail:{title:films[film].title,text:films[film].subtitle,params:{film:films[film].id}}}));break;case'film-evidence':details.open=true;old.scrollIntoView({behavior:'smooth'});break;}});
slider.addEventListener('input',()=>{rescue=0;beat=-1;setPlaying(false);elapsed=Number(slider.value)/1000*total;paint(elapsed);});
new IntersectionObserver(([entry])=>{inView=entry.isIntersecting;},{threshold:.05}).observe(host);
function hashFilm(){const id=new URLSearchParams(location.hash.slice(1)).get('film'),i=films.findIndex(f=>f.id===id);if(i>=0){loadFilm(i);host.scrollIntoView();}}
window.addEventListener('hashchange',hashFilm);loadFilm(0);hashFilm();requestAnimationFrame(frame);

document.addEventListener('unseen:watch',e=>{if(host.hidden)return;const sacrifice=['cat','jonathan'].includes(e.detail);loadFilm(sacrifice?1:0,false);seekBeat(sacrifice?1:e.detail==='david'?1:2);setPlaying(true);host.scrollIntoView({behavior:'smooth'});});
