export const episodeCuts=[
 {audio:"pacing-niko",revealAt:7,from:2,to:3,title:'A pause can make a clear vote feel close.',left:['Niko','Kate'],counts:[3,3],after:['Niko','Kate'],final:[10,3],question:'Stephen has not shown his vote.',answer:'Niko leaves. The final vote is not close.',note:'The episode ends during the vote count. Other targets are omitted from this two-player view.',source:'https://rts.org.uk/article/celebrity-traitors-recap-week-one'},
 {audio:"pacing-tie",revealAt:12,from:5,to:6,title:'This time, nobody can break the tie.',left:['Mark','David'],counts:[5,5],after:['Mark','David'],final:[5,5],question:'Two votes. Still tied.',answer:'A chest decides. Mark leaves.',note:'The first vote is 4–4 at the top. The restricted revote finishes 5–5. The next episode resolves the tie by chance.',source:'https://www.tvguide.co.uk/articles/celebrity-traitors-viewers-wondering-what-will-happen-vote-tie-latest-banishment/'},
 {audio:"pacing-murder",revealAt:10,from:6,to:7,title:'The vote ends. A new threat begins.',left:['Lucy','Nick','Kate'],question:'Three players face the murder.',answer:'Lucy leaves. Nick and Kate return.',note:'Episode 6 ends with the face-to-face murder setup. Episode 7 reveals Lucy as the victim.',source:'https://rts.org.uk/article/celebrity-traitors-recap-week-three'}
];
export function mountPacing(parent){
 const host=document.createElement('section');host.id='episode-pacing';host.className='episode-pacing';host.setAttribute('aria-labelledby','pacing-title');
 host.innerHTML='<div class="pacing-top"><h2 id="pacing-title">Where the episode stops.</h2><div><button class="text-button" id="pacing-play">▶ Watch</button><button class="text-button" id="pacing-voice" aria-pressed="true">Voice on</button></div></div><div class="pacing-tabs" role="group" aria-label="Episode breaks">'+episodeCuts.map((c,i)=>`<button data-cut="${i}" aria-pressed="${i===0}">Episode ${c.from} → ${c.to}</button>`).join('')+'</div><div class="pacing-screen"><div class="pacing-half before"><small id="pacing-before"></small><div id="pacing-left"></div><p id="pacing-question"></p></div><div class="pacing-cut"><span>EPISODE<br>BREAK</span></div><div class="pacing-half after" aria-hidden="true"><small id="pacing-after"></small><div id="pacing-right"></div><p id="pacing-answer"></p></div></div><p class="pacing-finding" id="pacing-finding"></p><details><summary>Sources</summary><p id="pacing-note"></p><a id="pacing-source" target="_blank" rel="noreferrer">Episode account ↗</a></details>';
 parent.append(host);let index=0,running=false,elapsed=0,last=0,revealed=false;
 const $=s=>host.querySelector(s),button=$('#pacing-play'),audio=new Audio();audio.preload="metadata";audio.id="pacing-audio";audio.hidden=true;host.append(audio);let voiced=true;
 function draw(i){index=i;elapsed=0;revealed=false;host.classList.remove('resolved');host.style.setProperty("--cut-progress",0);$(".after").setAttribute("aria-hidden","true");const c=episodeCuts[i];audio.src="assets/narration/"+c.audio+".mp3";$('#pacing-before').textContent='END OF EPISODE '+c.from;$('#pacing-after').textContent='EPISODE '+c.to;$('#pacing-question').textContent=c.question;$('#pacing-answer').textContent=c.answer;$('#pacing-finding').textContent=c.title;$('#pacing-note').textContent=c.note;$('#pacing-source').href=c.source;
 const rows=(names,counts,right)=>names.map((name,j)=>`<div class="pacing-person ${right&&i===2&&j===0?'pacing-victim':''}"><span>${name}</span>${counts?`<div class="pacing-ballots">${Array.from({length:counts[j]},(_,k)=>`<i style="--ballot:${k}"></i>`).join('')}</div><b>${counts[j]}</b>`:`<strong>${right?(j===0?'MURDERED':'SAFE'):'?'}</strong>`}</div>`).join('');
 $('#pacing-left').innerHTML=rows(c.left,c.counts,false);$('#pacing-right').innerHTML=rows(c.after||c.left,c.final,true);host.querySelectorAll('[data-cut]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.cut===i));button.textContent=running?'Ⅱ Pause':'▶ Watch';}
 function pause(){running=false;audio.pause();button.textContent=revealed&&(!voiced||audio.ended)?'↺ Replay':elapsed?'▶ Continue':'▶ Watch';}
 button.addEventListener('click',()=>{if(running)pause();else{if(revealed&&(!voiced||audio.ended))draw(index);document.dispatchEvent(new CustomEvent('unseen:navigate'));running=true;button.textContent='Ⅱ Pause';if(voiced)audio.play().catch(()=>{voiced=false;$('#pacing-voice').textContent='Voice unavailable';$('#pacing-voice').setAttribute('aria-pressed','false');});}});
 $('#pacing-voice').addEventListener('click',()=>{voiced=!voiced;$('#pacing-voice').textContent=voiced?'Voice on':'Voice off';$('#pacing-voice').setAttribute('aria-pressed',String(voiced));if(!voiced)audio.pause();else if(running){audio.currentTime=elapsed/1000;audio.play().catch(pause);}});
 host.addEventListener('click',e=>{const b=e.target.closest('[data-cut]');if(b){pause();draw(+b.dataset.cut);}});
 function tick(now){const dt=Math.min(now-last||0,100);last=now;if(running&&!document.hidden){if(voiced&&!audio.paused)elapsed=audio.currentTime*1000;else if(!voiced)elapsed+=dt;const revealAt=voiced?episodeCuts[index].revealAt*1000:3500;host.style.setProperty('--cut-progress',Math.min(1,elapsed/revealAt));if(elapsed>=revealAt&&!revealed){revealed=true;host.classList.add('resolved');$('.after').setAttribute('aria-hidden','false');}if((voiced&&audio.ended)||(!voiced&&revealed))pause();}requestAnimationFrame(tick);}
 audio.addEventListener('error',()=>{voiced=false;$('#pacing-voice').textContent='Voice unavailable';$('#pacing-voice').setAttribute('aria-pressed','false');});
 new IntersectionObserver(([e])=>{if(!e.isIntersecting)pause();}).observe(host);document.addEventListener('unseen:navigate',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});draw(0);requestAnimationFrame(tick);
}
