import {mountPacing} from './episode-pacing.js';
import {mountNavigation} from './navigation.js';
import {showStoryPoster,storyShareText} from './story-poster.js';
import {storyOrder,storyLinks,nextStoryIndex} from './story-route.js';
import {drawSeason} from './season-sequence.js';
import {drawStory} from './story-scenes.js';
import {players,byId} from './data.js';
import {archetypes} from './drama-data.js';
import {reels,coverRounds,teamRounds,winnerBallots} from './reveal-data.js';
const $=s=>document.querySelector(s);
const main=$('#main'),screen=document.createElement('section');screen.id='revelation-cinema';screen.className='revelation-cinema';
screen.innerHTML=`<div class="reveal-edition"><span>THE CELEBRITY TRAITORS · UK SERIES 1</span><span>FULL SERIES SPOILERS</span></div><div class="reel-picker" role="group" aria-label="Choose a revelation">${storyOrder.map((id,position)=>{const i=reels.findIndex(r=>r.id===id),r=reels[i];return `<button data-reel="${i}" aria-pressed="${position===0}"><small>0${position+1}</small>${r.name}</button>`;}).join('')}</div><div class="reveal-title"><span id="reveal-chapter">A FILM IN FOUR BEATS</span><h1 id="reveal-headline"></h1><p id="reveal-caption"></p></div><div class="reveal-stage"><div class="reveal-aura"></div><svg class="reveal-threads" viewBox="0 0 1000 500" preserveAspectRatio="none" aria-hidden="true"></svg><div id="reveal-cast"></div><div id="reveal-winners"></div><div id="reveal-season" hidden></div><div id="reveal-statement"></div><div id="reveal-target"></div></div><div class="reveal-history" id="reveal-history" aria-label="Round history"></div><div class="reveal-controls"><button id="reveal-play" class="primary-button">▶ Watch with narration</button><button id="reveal-silent" class="text-button">Watch silently</button><button id="reveal-restart" class="text-button" hidden>↺ Replay</button><span id="reveal-time"></span><button id="reveal-share" class="text-button">Share this story ↗</button><button id="reveal-poster" class="text-button">Save story image ↓</button></div><div id="reveal-beats" class="reveal-beats" role="group" aria-label="Film scenes"></div><div class="reveal-next" hidden><span id="reveal-takeaway"></span><button id="reveal-next-button" class="primary-button"></button></div><details class="reveal-transcript"><summary>Read the narration</summary><p id="reveal-transcript-text"></p></details><div class="reveal-context">Red frame: Traitor. Gold frame: Faithful. We see their roles; the players didn’t.<button id="reveal-receipts" class="text-button">Behind this revelation ↗</button></div>`;
main.prepend(screen);$('.reveal-title').after($('.reveal-controls'));
const sharing=document.createElement('div');sharing.className='story-sharing';sharing.append($('#reveal-share'),$('#reveal-poster'));$('.reveal-context').after(sharing);
const rules=document.createElement('details');rules.className='game-rules';rules.innerHTML='<summary>New to The Traitors?</summary><p>The Faithful must find the hidden Traitors and vote them out. The Traitors secretly remove players between votes. If a Traitor remains when the group ends the game, the Faithful lose.</p>';
$('.reel-picker').after(rules);

const receipt=document.createElement('dialog');receipt.id='reveal-receipt-dialog';receipt.setAttribute('aria-labelledby','reveal-receipt-title');receipt.innerHTML='<div class="dialog-heading"><span class="eyebrow">BEHIND THE REVELATION</span><button data-close-dialog class="close-button" aria-label="Close revelation evidence">×</button></div><div id="reveal-receipt-content"></div>';document.body.append(receipt);
const appendix=document.createElement('details');appendix.className='evidence-appendix';appendix.id='evidence-room';appendix.innerHTML='<summary>Explore how the game changed <span>Who voted together, who switched sides, and who survived ＋</span></summary><nav class="evidence-guide" aria-label="Explore the evidence"><a href="#reveal=fracture">Why Nick turned against Joe</a><a href="#reveal=murders">Watch what happens after a murder</a><a href="#theatre">Watch voting groups move</a><a href="#players">Compare the players</a><a href="#anatomy">Follow every round</a></nav>';
const deck=$('#cast-of-shadows');for(const el of [...main.children])if(el!==screen&&el!==deck){if(['ballot-lab','instinct'].includes(el.id)){el.hidden=true;continue;}appendix.append(el);}main.append(appendix);
// Lead with a small, readable relationship story before the full voting record.
for(const selector of ['#living-game','#the-apology','#ghosts','#players','#anatomy','.revelations','#theatre','.closing']){
 const section=appendix.querySelector(selector);if(section)appendix.append(section);
}
for(const selector of ['#living-game','#the-apology','.revelations','.old-theatre']){const old=appendix.querySelector(selector);if(old)old.hidden=true;}
$('#cast-title').innerHTML='Meet the players.';
$('.cast-invitation p').innerHTML='What helped them stay? What got them out?<br>Choose a player.';
$('nav').innerHTML='<a href="#revelation-cinema">Watch the stories</a><a href="#cast-of-shadows">Meet the players</a><a href="#evidence-room">Explore the votes</a>';
const audio=new Audio();audio.id='reveal-audio';audio.hidden=true;screen.append(audio);audio.preload='auto';let reel=0,beat=0,playing=false,voiced=true,started=false,done=false,local=0,last=0,visible=true,stageKey='',narration={},duration=18000;
const cast=$('#reveal-cast'),threads=$('.reveal-threads'),statement=$('#reveal-statement'),target=$('#reveal-target'),history=$('#reveal-history');
fetch('assets/narration/script.json').then(r=>r.json()).then(data=>{narration=Object.fromEntries(data.clips.map(c=>[c.id,c.text]));updateText();}).catch(()=>{$('#reveal-transcript-text').textContent='Narration unavailable. The visual captions remain available.';});
const art=id=>archetypes.findIndex(a=>a.id===id);
function personHTML(id){const p=byId[id],i=art(id);return `<div class="reveal-person ${p.role==='T'?'person-traitor':''} ${i<0?'person-initial':''}" data-reveal-person="${id}" aria-hidden="true" style="--art-x:${i%3*50}%;--art-y:${i<3?0:100}%"><div class="reveal-portrait">${i<0?`<span>${p.name.split(' ').map(s=>s[0]).join('')}</span>`:''}</div><small>${p.role==='T'?'TRAITOR':'FAITHFUL'}</small><strong>${p.short}</strong><em></em></div>`;}
function updateText(){const b=reels[reel].beats[beat];$('#reveal-chapter').textContent=started?`STORY ${storyOrder.indexOf(reels[reel].id)+1} · ${beat+1} / ${reels[reel].beats.length}`:(reels[reel].id==='fracture'?'START WITH THE FINAL VOTE':'CHOOSE A STORY OR PRESS PLAY');$('#reveal-headline').textContent=started?b.title:reels[reel].hook;$('#reveal-caption').textContent=started?b.caption:reels[reel].strap;$('#reveal-transcript-text').textContent=narration[b.audio]||'';screen.querySelectorAll('[data-reveal-beat]').forEach((el,i)=>el.setAttribute('aria-current',i===beat?'step':'false'));}
function createCast(){cast.innerHTML=players.map(p=>personHTML(p.id)).join('');}
function place(id,x,y,size=1,on=true,caption=''){const el=cast.querySelector(`[data-reveal-person="${id}"]`);el.style.left=x+'%';el.style.top=y+'%';el.style.setProperty('--person-scale',size);el.classList.toggle('on-stage',on);el.setAttribute('aria-hidden',String(!on));el.querySelector('em').textContent=caption;}
function clearStage(){cast.querySelectorAll('.reveal-person').forEach(el=>{el.classList.remove('on-stage','story-out');el.setAttribute('aria-hidden','true');});threads.innerHTML='';statement.innerHTML='';target.innerHTML='';$('#reveal-winners').hidden=true;$('#reveal-season').hidden=true;cast.hidden=false;}
function roundRail(type){history.innerHTML=(type==='team'?teamRounds:coverRounds).map((r,i)=>`<span data-round-light="${i}"><small>${r.label}</small><i></i></span>`).join('');}
function illuminate(index){history.querySelectorAll('[data-round-light]').forEach((el,i)=>{el.classList.toggle('seen',i<=index);el.classList.toggle('current',i===index);});}
function cover(index){const r=coverRounds[index];clearStage();place('alan',50,47,1.35);const n=r.companions.length;let links='';r.companions.forEach((id,i)=>{let a=-Math.PI/2+(i+.5)*Math.PI*2/n;const x=50+Math.cos(a)*37,y=47+Math.sin(a)*30;place(id,x,y,n>5?.67:.85);links+=`<path d="M500 235 Q${x*10} 235 ${x*10} ${y*5}"/>`;});threads.innerHTML=links;target.innerHTML=`<small><b>${n}</b> ${n===1?'PERSON':'PEOPLE'} VOTED WITH ALAN AGAINST</small><strong>${byId[r.target].name}</strong>`;statement.innerHTML='';illuminate(index);}
function team(index,mode){clearStage();const ids=['alan','cat','jonathan'],positions=[[23,43],[50,43],[77,43]];if(mode==='team'){const targets=teamRounds[index].targets,groups=[...new Set(targets)].map(t=>ids.map((id,i)=>targets[i]===t?i:-1).filter(i=>i>=0)).sort((a,b)=>b.length-a.length);if(groups.length===2){groups[0].forEach((i,j)=>positions[i]=[25+j*23,37]);positions[groups[1][0]]=[80,63];}else{positions[0]=[17,37];positions[1]=[50,58];positions[2]=[83,37];}}ids.forEach((id,i)=>place(id,...positions[i],1.15,true,mode==='team'?`VOTED ${byId[teamRounds[index].targets[i]].short.toUpperCase()}`:''));if(mode==='team'){const t=teamRounds[index].targets;let lines='';for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)if(t[i]===t[j])lines+=`<path d="M${positions[i][0]*10} ${positions[i][1]*5} L${positions[j][0]*10} ${positions[j][1]*5}"/>`;threads.innerHTML=lines;illuminate(index);target.innerHTML='<small>SAME TARGET?</small><strong>'+ (new Set(t).size===3?'Three different names.':'Two agree. One does not.')+'</strong>';}else if(mode==='team-end'){statement.innerHTML='<span class="reveal-big">0<span>/6</span></span><small>ROUNDS WITH ONE SHARED TARGET</small>';target.innerHTML='';history.querySelectorAll('span').forEach(el=>el.classList.add('seen'));}else target.innerHTML='<strong>One secret. Three people.</strong>';}
function createWinners(){const wrap=$('#reveal-winners');wrap.innerHTML=winnerBallots.map(w=>`<div class="winner-column"><div class="winner-seal ${w.role==='T'?'seal-traitor':''}"><small>${w.series}</small><strong>${w.name}</strong><em>${w.role==='T'?'TRAITOR':'FAITHFUL'}</em></div><div class="winner-lights">${w.ballots.map((b,i)=>`<span class="winner-light" data-company="${b.company}" aria-label="${w.name}, ballot ${i+1}: ${b.company?'shared target':'lone vote'}"></span>`).join('')}</div></div>`).join('');}
function winners(progress,mode){clearStage();cast.hidden=true;$('#reveal-winners').hidden=false;const lights=[...screen.querySelectorAll('.winner-light')],company=lights.filter(el=>el.dataset.company==='true');const removed=mode==='winners'?0:mode==='winners-end'?52:Math.min(52,Math.floor(Math.max(0,progress-.08)/.56*52));company.forEach((el,i)=>el.classList.toggle('light-departed',i<removed));lights.filter(el=>el.dataset.company==='false').forEach(el=>el.classList.toggle('light-alone',removed>0));statement.innerHTML=`<span class="reveal-big">${55-removed}<span>/55</span></span><small>${removed?'VOTES LEFT ALONE':'BALLOTS CAST BY WINNERS'}</small>`;target.innerHTML=removed===52?'<strong>52 had company. Just 3 did not.</strong>':'<small>ONE LIGHT = ONE VOTE</small>';}
function paint(){const b=reels[reel].beats[beat],p=Math.min(local/duration,1),mode=b.mode;screen.dataset.revealMode=mode;screen.dataset.started=started;let key=mode;
 if(mode==='season'){const count=Math.min(b.to,b.from+b.cues.filter(c=>p>=c).length);key+='-'+count;if(key!==stageKey){clearStage();cast.hidden=true;$('#reveal-season').hidden=false;drawSeason(count,$('#reveal-season'));}}
 else if(mode==='story'){key+='-'+b.frame;if(key!==stageKey)drawStory(b.frame,{cast,threads,target,statement,clearStage,place});}
 else if(mode==='cover'){const at=b.indices[Math.min(b.indices.length-1,Math.floor(p*b.indices.length))];key+='-'+at;if(key!==stageKey)cover(at);}
 else if(mode==='team'){const at=Math.min(5,Math.floor(p*6));key+='-'+at;if(key!==stageKey)team(at,mode);}
 else if(mode.startsWith('winners')){key+='-'+Math.floor(p*100);if(key!==stageKey)winners(p,mode);}
 else if(key!==stageKey){clearStage();if(mode==='intro'){place('alan',50,42,1.8);target.innerHTML='<small>ALAN CARR · COMEDIAN</small><strong>A Traitor hiding in company.</strong>';}
 else if(mode==='cover-end'){cover(8);statement.innerHTML='<span class="reveal-big">9<span>/9</span></span><small>VOTES WITH COMPANY</small>';history.querySelectorAll('span').forEach(el=>el.classList.add('seen'));target.innerHTML='<strong>Always someone beside him.</strong>';}
 else team(0,mode);}
 stageKey=key;$('#reveal-time').textContent=started?`${Math.floor(local/1000)} / ${Math.ceil(duration/1000)}s`:'';const active=screen.querySelector(`[data-reveal-beat="${beat}"]`);if(active)active.style.setProperty('--beat-progress',(p*100)+'%');}
function updateControl(){screen.classList.toggle('cinema-enabled',started);const play=$('#reveal-play');play.textContent=playing?'Ⅱ Pause':done?(nextStoryIndex(reels,reel)>=0?'Next revelation →':'↺ Watch again'):started?'▶ Continue': '▶ Watch with narration';$('#reveal-silent').textContent=voiced?'Watch silently':'Turn narration on';$('#reveal-restart').hidden=!started;screen.classList.toggle('is-playing',playing);}
async function playAudio(){try{await audio.play();}catch{playing=false;$('#reveal-caption').textContent='Press Continue to start the narration.';updateControl();}}
function setBeat(i,autoplay=false){audio.pause();beat=i;local=0;done=false;duration=reels[reel].beats[i].seconds*1000;stageKey='';$('.reveal-next').hidden=true;audio.src=`assets/narration/${reels[reel].beats[i].audio}.mp3`;playing=autoplay;updateText();paint();updateControl();if(playing&&voiced)playAudio();}
function loadReel(i){audio.pause();reel=i;started=false;playing=false;done=false;createCast();roundRail(i===1?'team':'cover');history.hidden=i>=2;$('#reveal-beats').innerHTML=reels[i].beats.map((b,j)=>`<button data-reveal-beat="${j}" aria-label="Scene ${j+1}: ${b.title}"><span>${b.title}</span></button>`).join('');screen.querySelectorAll('[data-reel]').forEach((el,j)=>el.setAttribute('aria-pressed',+el.dataset.reel===i));setBeat(0);}
function finishBeat(){if(beat<reels[reel].beats.length-1)setBeat(beat+1,true);else{audio.pause();playing=false;done=true;local=duration;paint();updateControl();$('.reveal-next').hidden=false;$('#reveal-takeaway').textContent=reels[reel].takeaway;$('#reveal-next-button').textContent=nextStoryIndex(reels,reel)>=0?storyLinks[reels[reel].id].question+' →':'Meet the players ↓';}}
function pause(){playing=false;audio.pause();updateControl();}
document.addEventListener('unseen:network-play',pause);
document.addEventListener('unseen:navigate',pause);
audio.addEventListener('loadedmetadata',()=>{if(Number.isFinite(audio.duration))duration=audio.duration*1000;});audio.addEventListener('ended',()=>{if(playing&&voiced)finishBeat();});audio.addEventListener('error',()=>{if(voiced){pause();$('#reveal-caption').textContent='Narration could not load. You can watch silently.';}});
screen.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.reel!==undefined)loadReel(+b.dataset.reel);if(b.dataset.revealBeat!==undefined){started=true;setBeat(+b.dataset.revealBeat,false);$('.reveal-title').scrollIntoView({behavior:'smooth',block:'start'});}switch(b.id){case'reveal-poster':pause();showStoryPoster(reels[reel].id).catch(()=>{$('#reveal-caption').textContent='The image could not load. Please try again.';});break;case'reveal-receipts':pause();showReceipt();break;case'reveal-play':if(playing){pause();break;}if(done&&nextStoryIndex(reels,reel)>=0)loadReel(nextStoryIndex(reels,reel));started=true;if(done)setBeat(0);playing=true;updateText();updateControl();if(voiced)playAudio();break;case'reveal-silent':voiced=!voiced;if(done)setBeat(0);started=true;playing=true;updateText();if(voiced){audio.currentTime=Math.min(local/1000,audio.duration||0);if(playing)playAudio();}else audio.pause();updateControl();break;case'reveal-restart':started=true;setBeat(0,true);break;case'reveal-next-button':if(nextStoryIndex(reels,reel)>=0){loadReel(nextStoryIndex(reels,reel));started=true;playing=true;updateText();updateControl();if(voiced)playAudio();}else{pause();deck.scrollIntoView({behavior:'smooth'});}break;case'reveal-share':pause();document.dispatchEvent(new CustomEvent('unseen:share',{detail:{title:reels[reel].hook,text:storyShareText(reels[reel].id),params:{reveal:reels[reel].id}}}));break;}});
function tick(now){const dt=Math.min(now-last||16,100);last=now;if(visible&&!document.hidden){if(playing){if(document.querySelector('dialog[open]'))pause();else if(voiced)local=audio.currentTime*1000;else{local+=dt;if(local>=duration)finishBeat();}}paint();}requestAnimationFrame(tick);}
new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(!visible&&playing)pause();},{threshold:.05}).observe(screen);document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)pause();});
function hash(){const params=new URLSearchParams(location.hash.slice(1));const legacy=params.get('film');const id=params.get('reveal')||(legacy==='fracture'?'fracture':legacy==='warning'?'murders':null),index=reels.findIndex(r=>r.id===id&&storyOrder.includes(id));if(index>=0){loadReel(index);screen.scrollIntoView();}else{const el=params.has('network')?document.getElementById('theatre'):document.getElementById(location.hash.slice(1));if(el&&appendix.contains(el)){appendix.open=true;el.scrollIntoView();}}}
window.addEventListener('hashchange',hash);createWinners();loadReel(reels.findIndex(r=>r.id==='fracture'));hash();requestAnimationFrame(tick);

function showReceipt(){
 const wiki='https://en.wikipedia.org/wiki/The_Celebrity_Traitors_series_1';let content='';
 if(reel===0)content='<p>Each row is an ordinary round. The names below cast the same target ballot as Alan; this is co-voting, not a claim about a private agreement.</p><table><thead><tr><th>Round</th><th>Target</th><th>Company</th></tr></thead><tbody>'+coverRounds.map(r=>`<tr><td>${r.label}</td><td>${byId[r.target].name}</td><td>${r.companions.map(id=>byId[id].name).join(', ')}</td></tr>`).join('')+'</tbody></table><p>The restricted revote is excluded.</p>';
 else if(reel===1)content='<p>The six ordinary rounds in which all three original Traitors could vote. No row has three identical targets.</p><table><thead><tr><th>Round</th><th>Alan</th><th>Cat</th><th>Jonathan</th></tr></thead><tbody>'+teamRounds.map(r=>`<tr><td>${r.label}</td>${r.targets.map(id=>`<td>${byId[id].short}</td>`).join('')}</tr>`).join('')+'</tbody></table>';
 else if(reel===3)content='<p>Joe, David and Nick voted for Cat in the final five. At the final four, Nick and David voted with Alan against Joe. Joe voted for Alan.</p><p>Nick later said that Joe’s apology to Cat made him suspect Joe was a fellow Traitor.</p><p><a href="https://www.bigissue.com/culture/tv/celebrity-traitors-nick-mohammed-interview/" target="_blank" rel="noreferrer">Read Nick’s account · The Big Issue ↗</a></p>';
 else if(reel===5)content='<p>The nine banishments are shown in order. Mark’s departure includes the tied revote and chest tiebreak. Murders are not shown here.</p><p>The first five banishments removed Faithfuls. Jonathan was next, followed by Kate, Cat and Joe. Alan remained.</p><p>This shows game results. It does not measure the audience’s feelings or the pace of the programme’s editing.</p>';
 else if(reel===4)content='<p>Ruth last voted for Jonathan in round 02. After her murder, he survived rounds 03, 04 and 05, plus the restricted revote.</p><p>Joe and Lucy voted for Jonathan in round 05. Lucy was murdered before round 06, when six players voted for Jonathan: Joe, Nick, Cat, Alan, Celia and Kate.</p><p>A reported turret discussion describes Jonathan’s concern that Ruth would keep accusing him. This account supports his reason for wanting her removed. His later survival does not establish that the murder caused it.</p><p><a href="https://www.standard.co.uk/culture/music/jonathan-ross-clare-balding-alan-carr-bbc-one-celia-imrie-b1253383.html" target="_blank" rel="noreferrer">Reported turret discussion · PA / The Standard ↗</a></p>';
 else content='<p>Winners from UK1, UK2 and Celebrity1. A lone vote means nobody else named that target in that round. Restricted revotes and end/continue decisions are excluded.</p><table><thead><tr><th>Winner</th><th>Ballots</th><th>Alone</th></tr></thead><tbody>'+winnerBallots.map(w=>`<tr><td>${w.name} · ${w.series}</td><td>${w.ballots.length}</td><td>${w.ballots.filter(b=>!b.company).length}</td></tr>`).join('')+'</tbody></table><p>An exploratory description of three seasons, not evidence that company causes victory. Earlier-season rows reconcile with their published tallies; an independent source cross-check remains pending.</p><p><a href="https://thetraitors.fandom.com/wiki/The_Traitors_(UK)/Series_1#Voting_History" target="_blank" rel="noreferrer">UK1 source ↗</a> · <a href="https://thetraitors.fandom.com/wiki/The_Traitors_(UK)/Series_2#Voting_History" target="_blank" rel="noreferrer">UK2 source ↗</a></p>';
 $('#reveal-receipt-content').innerHTML='<h2 id="reveal-receipt-title">'+reels[reel].name+'</h2>'+content+`<p><a href="${wiki}" target="_blank" rel="noreferrer">Celebrity1 voting record ↗</a></p>`;receipt.showModal();
}
document.addEventListener('unseen:watch',e=>{pause();const i={alan:0,cat:1,jonathan:4,joe:3,nick:3,david:3}[e.detail]??0;loadReel(i);started=true;playing=true;updateText();updateControl();if(voiced)playAudio();screen.scrollIntoView({behavior:'smooth'});});

$('#ghosts').hidden=true;
appendix.querySelector('summary').innerHTML='Explore the game';
mountPacing(appendix);
mountNavigation();
